sonar.projectKey=CodingABoveHEAd_ScholarShelf
sonar.projectName=ScholarShelf
sonar.projectVersion=1.0
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=build/classes/java/main
sonar.java.libraries=build/libs/**/*.jar
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/*Entity.java,**/*DTO.java,**/*Config.java
